version: '3'
services:
 mongodb:
  image: mongo:4
  ports: 
    - "27017:27017"
 backend:
  image: subicura/guestbook-backend:latest
  environment: 
    PORT: 8000
    GUESTBOOK_DB_ADDR: mongodb:27017
  restart: always
 frontend:
  image: subicura/guestbook-frontend:latest
  ports: 
    - "62000:8000"
  environment:
    PORT: 8000 
    GUESTBOOK_API_ADDR: backend:8000