# 1. node 설치
# 사용할 이미지 : ubuntu
FROM ubuntu:20.04
# 실행할 명령어
RUN apt-get update
#nodejs와 npm 설치
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs npm

# 2. 소스 복사
# 내 디렉토리에 있는 파일(.)을 /usr/src/app에 복사
COPY . /usr/src/app

# 3. Nodejs 패키지 설치
# 경로로 이동
WORKDIR /usr/src/app
RUN npm install

# 4. WEB 서버 실행 (Listen 포트 정의)
EXPOSE 3000
CMD node app.js 